if __name__ == "__main__":
    fp = open("text.txt", "rt")
    line = fp.readline()
    print(line.strip())
    line = fp.readline()
    print(line.strip())
    line = fp.readline()
    print(line.strip())
    line = fp.readline()
    print(line.strip())
    fp.close()
